[General]
showlogo=shown
showClock=true
logo=/usr/share/sddm/themes/neoos/neoos.png
type=image
color=#00e640
fontSize=10
background=/usr/share/wallpapers/Next/contents/images/5120x2880.png
needsFullUserModel=false
